### ISSUE TITLE
在tableview/collection中的cell富文本label主题更改未生效

### ISSUE THREAD

**Issue by Brilliance-Yin** [internetWei/llDark#10]
需要自行刷新

**Comment by internetWei** [comment]
您好，我写了一个DarkTest项目，使用UITableView并没有复现您提到的问题。请[点击链接](https://gitee.com/internetWei/images/raw/master/uPic/202102271119.gif)查看测试Gif，我的运行设备是iPhone12机型iOS14.4系统的模拟器。测试代码已上传到<https://github.com/internetWei/DarkTest>，您可以下载运行查看。

请检查您的<LLDark>版本是不是最新的，如果还有问题请在提问的同时附上相关代码和截图，以方便我定位问题。

**Comment by Brilliance-Yin** [comment]
好的，谢谢，知道问题所在了，设置textColor无效，要在attributes中添加NSForegroundColorAttributeName颜色就没问题了
