### ISSUE TITLE
引入LLDark导致preferredStatusBarStyle不执行

### ISSUE THREAD

**Issue by ovveii** [internetWei/llDark#11]
建了一个测试Demo,然后引入LLDark, preferredStatusBarStyle 就不执行了。LLDark中的Demo的changeStatusBarStyle方法改变状态颜色也未生效
- (UIStatusBarStyle)preferredStatusBarStyle
{
    return UIStatusBarStyleLightContent;
}

**Comment by internetWei** [comment]
您好，请问您是通过什么方式触发的`preferredStatusBarStyle`方法呢？

我也写了一个Demo，就算我不引入`LLDark`也会发生`preferredStatusBarStyle`不调用的情况，如果方便的话麻烦您把您的测试Demo分享一下给我，也方便我排查问题。

**Comment by ovveii** [comment]
> 您好，请问您是通过什么方式触发的`preferredStatusBarStyle`方法呢？
> 
> 我也写了一个Demo，就算我不引入`LLDark`也会发生`preferredStatusBarStyle`不调用的情况，如果方便的话麻烦您把您的测试Demo分享一下给我，也方便我排查问题。

嗯，测试Demo已发送你foxmail了，辛苦啦

**Comment by ovveii** [comment]
新建Demo默认会触发，但还是配置了&nbsp;info.plist配置 View controller-based status bar appearance 为YES




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 上午6:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [internetWei/llDark] 引入LLDark导致preferredStatusBarStyle不执行 (#11)





 
您好，请问您是通过什么方式触发的preferredStatusBarStyle方法呢？

**Comment by internetWei** [comment]
您好，您提到的preferredStatusBarStyle不执行的问题已经在1.1.6版本中修复了。我这边测试没有问题，您可以下载最新的代码再测试一下。

**Comment by ovveii** [comment]
好的，谢谢了
