### ISSUE TITLE
appearanceBindUpdater和themeDidChange感觉很类似

### ISSUE THREAD

**Issue by FrizzleFur** [internetWei/llDark#2]
看了下代码，想问下appearanceBindUpdater和themeDidChange所有的object都有的属性，都是在主题切换的时候的回调吧？ 这两个有什么区别吗？ appearanceBindUpdater是通过isNeedRefresh控制，是不是themeDidChange里判断当前的theme和change的theme是否一致就可以控制每个object的themeDidChange？

**Comment by internetWei** [comment]
稍等，现在同事都在午休，等下14点前用电脑给您答复。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: MMao <notifications@github.com&gt;
发送时间: 2020年12月17日 10:46
收件人: internetWei/llDark <llDark@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[internetWei/llDark] appearanceBindUpdater和themeDidChange感觉很类似 (#2)





 
看了下代码，想问下appearanceBindUpdater和themeDidChange所有的object都有的属性，都是在主题切换的时候的回调吧？ 这两个有什么区别吗？ appearanceBindUpdater是通过isNeedRefresh控制，是不是themeDidChange里判断当前的theme和change的theme是否一致就可以控制每个object的themeDidChange？

**Comment by internetWei** [comment]
appearanceBindUpdater和themeDidChange的区别：
    • appearanceBindUpdater仅在View需要刷新时才会调用，themeDidChange不管view是否需要刷新，只要修改后的主题和当前主题不一样就会调用。
    
 有这么一种情况：当前APP是“跟随系统”，系统是“深色模式”，然后APP切换到了“深色模式”，这时候主题模式是变化了的(因为从“跟随系统”->“深色模式”)。所以会调用themeDidChange。但是View实际上并没有刷新，因为上一次是深色UI，变化后还是深色UI。所以不会调用appearanceBindUpdater。

 不知道我这么说您是否明白。如果还有什么不明白的地方或者建议欢迎通过任何方式通知我。

**Comment by FrizzleFur** [comment]
大概理解，appearanceBindUpdater是当前视图的userInterfaceStyle变化的回调吧，LLUserInterfaceStyleUnspecified 感觉不太表意，如果默认跟随系统，我觉得可以命名成LLUserInterfaceStyleDefaultSystem.

**Comment by internetWei** [comment]
LLUserInterfaceStyleUnspecified的命名参考了系统的UIUserInterfaceStyleUnspecified，当时也考虑过命名为LLUserInterfaceStyleDefaultSystem，但是考虑到用户使用时命名和系统一致更加容易理解，所以采用了LLUserInterfaceStyleUnspecified。
