### ISSUE TITLE
可以为UIActivityIndicatorView和UIVisualEffectView添加支持暗黑模式吗？

### ISSUE THREAD

**Issue by carlchou00** [internetWei/llDark#3]
可以为UIActivityIndicatorView和UIVisualEffectView添加支持暗黑模式吗？

**Comment by internetWei** [comment]
UIActivityIndi​​catorView支持暗黑模式，使用方式如下：
```
UIActivityIndicatorView *activeView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    activeView.color = UIColor.greenColor.themeColor(UIColor.whiteColor);
    [activeView startAnimating];
    activeView.backgroundColor = UIColor.redColor;
    activeView.frame = CGRectMake(100, 300, 100, 100);
    [self.view addSubview:activeView];
```
UIVisualEffectView没有UIColor或者UIImage属性，我不太明白您说的UIVisualEffectView支持暗黑模式是什么意思？
如果您要在切换暗黑模式时更换UIVisualEffectView，可以参考appearanceBindUpdater或者themeDidChange属性。

**Comment by carlchou00** [comment]
> UIActivityIndi​​catorView支持暗黑模式，使用方式如下：
> 
> ```
> UIActivityIndicatorView *activeView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
>     activeView.color = UIColor.greenColor.themeColor(UIColor.whiteColor);
>     [activeView startAnimating];
>     activeView.backgroundColor = UIColor.redColor;
>     activeView.frame = CGRectMake(100, 300, 100, 100);
>     [self.view addSubview:activeView];
> ```
> 
> UIVisualEffectView没有UIColor或者UIImage属性，我不太明白您说的UIVisualEffectView支持暗黑模式是什么意思？
> 如果您要在切换暗黑模式时更换UIVisualEffectView，可以参考appearanceBindUpdater或者themeDidChange属性。

好的，我试试您说的方式，谢谢！
