### ISSUE TITLE
YYLable切换颜色时，无法生效

### ISSUE THREAD

**Issue by carlchou00** [internetWei/llDark#5]
写demo时使用yylabel没有问题
在项目中，由于在字典转模型时，YYTextLayout是根据数据生成之后，存在模型里的，在cell赋值时会取模型中的YYTextLayout实例赋值给yylabel，不知道为什么切换暗黑模式时，没有效果，或者说只有可见的cell有效果，再来回滚动时，重新给cell赋值模型，又会变回之前的颜色值，请问有什么强制刷新所有控件的方法吗？

**Comment by internetWei** [comment]
您好，我没有复现您提到的问题，麻烦您发一下有问题的Demo到我的邮箱上<internetwei@foxmail.com>。我会尽快处理您的问题。

在问题解决之前您可以尝试使用appearanceBindUpdater属性看看能不能解决您现在的问题。

**Comment by carlchou00** [comment]
> 您好，我没有复现您提到的问题，麻烦您发一下有问题的Demo到我的邮箱上[internetwei@foxmail.com](mailto:internetwei@foxmail.com)。我会尽快处理您的问题。
> 
> 在问题解决之前您可以尝试使用appearanceBindUpdater属性看看能不能解决您现在的问题。

用themeDidChange解决了，谢谢大佬！

**Comment by internetWei** [comment]
您好。
我最近准备重新整理升级LLDark，麻烦您详细描述一下您上次遇到问题。我这边也好记录并解决。
