### ISSUE TITLE
CAGradientLayer的colors不使用themeColor创建颜色时，切换手机的暗黑模式，会导致颜色丢失

### ISSUE THREAD

**Issue by carlchou00** [internetWei/llDark#8]
重现步骤：demo中第301行：
改之前：layer.colors = @[UIColor.redColor.themeColor(UIColor.blueColor), UIColor.greenColor, UIColor.blueColor.themeColor(UIColor.redColor)];

改之后：layer.colors = @[UIColor.redColor, UIColor.greenColor, UIColor.blueColor];

运行代码，在亮色和夜间模式间切换时，CAGradientLayer的颜色丢失。

注释掉：CAGradientLayer +Dark.m的第36行处status判断条件之后正常
大佬看下这里是不是有点问题。

**Comment by internetWei** [comment]
您好。
    感谢您的反馈，确实有这个问题，目前已经在1.1.1版本中修复，请及时更新最新版本。

**Comment by carlchou00** [comment]
> 您好。
> 感谢您的反馈，确实有这个问题，目前已经在1.1.1版本中修复，请及时更新最新版本。

谢谢大佬，非常感谢！
